<?php
/**
 * WealthDash — t378: WhatsApp / Email Report Sharing
 * File: api/sharing/report_share.php
 * Actions: share_whatsapp_link, share_email_send, share_pdf_link
 *
 * WhatsApp: Uses wa.me deep link (no API key needed) — generates a
 * pre-filled message with portfolio summary that opens WhatsApp.
 * Email: Uses PHP mail() / SMTP (app_settings smtp_* config from t52).
 */
defined('WEALTHDASH') or die('Direct access not allowed.');

$action      = clean($_POST['action'] ?? $_GET['action'] ?? '');
$userId      = (int)$_SESSION['user_id'];
$portfolioId = get_user_portfolio_id($userId);

function _build_summary_text(int $userId, int $portfolioId): string {
    $v  = (float)(DB::fetchVal("SELECT COALESCE(SUM(h.units*COALESCE(n.nav,h.avg_cost_per_unit)),0) FROM mf_holdings h LEFT JOIN mf_nav_latest n ON n.mf_id=h.mf_id WHERE h.user_id=? AND h.portfolio_id=? AND h.units>0",[$userId,$portfolioId])??0);
    $inv= (float)(DB::fetchVal("SELECT COALESCE(SUM(h.units*h.avg_cost_per_unit),0) FROM mf_holdings h WHERE h.user_id=? AND h.portfolio_id=? AND h.units>0",[$userId,$portfolioId])??0);
    $gain = $v - $inv;
    $gainPct = $inv>0 ? round($gain/$inv*100,2) : 0;
    $sips = (int)(DB::fetchVal("SELECT COUNT(*) FROM mf_sips WHERE user_id=? AND portfolio_id=? AND status='active'",[$userId,$portfolioId])??0);

    $lines = [];
    $lines[] = "📊 *My WealthDash Portfolio Summary*";
    $lines[] = "";
    $lines[] = "💰 Portfolio Value: ₹" . number_format($v,0);
    $lines[] = "📈 Total Gain: " . ($gain>=0?'+':'') . "₹" . number_format($gain,0) . " ({$gainPct}%)";
    $lines[] = "🔁 Active SIPs: {$sips}";
    $lines[] = "";
    $lines[] = "Generated by WealthDash on " . date('d M Y');
    return implode("\n", $lines);
}

switch ($action) {

    // ── Generate WhatsApp share link ──────────────────────────────────
    case 'share_whatsapp_link': {
        $reportType = clean($_POST['report_type'] ?? 'summary');
        $phone      = clean($_POST['phone'] ?? ''); // optional, blank = open chat picker

        $text = _build_summary_text($userId, $portfolioId);

        // Custom message override
        $customMsg = clean($_POST['custom_message'] ?? '');
        if ($customMsg) $text = $customMsg . "\n\n" . $text;

        $encoded = rawurlencode($text);
        $waUrl = $phone
            ? "https://wa.me/{$phone}?text={$encoded}"
            : "https://wa.me/?text={$encoded}";

        // Log share event
        DB::execute("INSERT INTO report_shares(user_id,channel,report_type,created_at) VALUES(?,?,?,NOW())", [$userId,'whatsapp',$reportType]);

        json_response(true,'ok',['whatsapp_url'=>$waUrl,'text'=>$text]);
        break;
    }

    // ── Send report via email ──────────────────────────────────────────
    case 'share_email_send': {
        csrf_verify();
        RateLimit::check('add_transaction', $userId); // reuse moderate limit

        $toEmail = clean($_POST['to_email'] ?? '');
        $reportType = clean($_POST['report_type'] ?? 'summary');
        $customMsg = clean($_POST['custom_message'] ?? '');

        if (!$toEmail || !filter_var($toEmail, FILTER_VALIDATE_EMAIL)) json_response(false, 'Valid email required.');

        $emailEnabled = DB::fetchVal("SELECT setting_val FROM app_settings WHERE setting_key='email_enabled'");
        if ($emailEnabled !== '1') {
            json_response(false, 'Email sending is disabled. Admin must enable it in Global Settings.');
        }

        $summary = _build_summary_text($userId, $portfolioId);
        $summaryHtml = nl2br(htmlspecialchars($summary));

        $fromName = DB::fetchVal("SELECT setting_val FROM app_settings WHERE setting_key='smtp_from_name'") ?: 'WealthDash';
        $subject = "Your WealthDash Portfolio Report — " . date('d M Y');

        $body = "<html><body style='font-family:Arial,sans-serif;'>";
        if ($customMsg) $body .= "<p>" . nl2br(htmlspecialchars($customMsg)) . "</p><hr>";
        $body .= "<div style='white-space:pre-wrap;'>{$summaryHtml}</div>";
        $body .= "</body></html>";

        $headers = "MIME-Version: 1.0\r\n";
        $headers .= "Content-Type: text/html; charset=UTF-8\r\n";
        $headers .= "From: {$fromName} <noreply@" . parse_url(APP_URL, PHP_URL_HOST) . ">\r\n";

        $sent = @mail($toEmail, $subject, $body, $headers);

        DB::execute("INSERT INTO report_shares(user_id,channel,report_type,recipient,success,created_at) VALUES(?,?,?,?,?,NOW())",
            [$userId,'email',$reportType,$toEmail,$sent?1:0]);

        if (!$sent) json_response(false, 'Email send failed. Check SMTP configuration with admin.');
        json_response(true, "Report sent to {$toEmail}! 📧");
        break;
    }

    // ── Generate shareable PDF download link (for future PDF export) ──
    case 'share_pdf_link': {
        // Placeholder: generates a signed, time-limited link for PDF export
        // Actual PDF generation should hook into report_fy or similar export endpoint
        $token = bin2hex(random_bytes(16));
        $expiresAt = date('Y-m-d H:i:s', strtotime('+24 hours'));

        DB::execute("INSERT INTO report_share_tokens(user_id,token,expires_at,created_at) VALUES(?,?,?,NOW())", [$userId,$token,$expiresAt]);

        $shareUrl = APP_URL . "?page=report_fy&share_token={$token}";
        json_response(true,'ok',['share_url'=>$shareUrl,'expires_at'=>$expiresAt]);
        break;
    }

    default: json_response(false,'Unknown action.',[],400);
}
